### ISSUE TITLE
No color in terminal

### ISSUE THREAD

**Issue by lejard-h** [dart-bridge/cupid#11]
Hello

I am using cupid [here](https://github.com/walletek/polymer_app/blob/master/bin/polymer_app.dart).
So great except that I have no color in my terminal while color work perfectly  with the bridge cli.

Thank you for your help :)

**Comment by emilniklas** [comment]
Hello! It seems to be working fine for me. Is this not what you see?

<img width="1069" alt="screen shot 2016-01-05 at 23 05 44" src="https://cloud.githubusercontent.com/assets/4621839/12128954/e3f67a46-b400-11e5-951a-531e7379894d.png">

What terminal and OS are you using?

**Comment by lejard-h** [comment]
<img width="1039" alt="screen shot 2016-01-06 at 00 50 19" src="https://cloud.githubusercontent.com/assets/7336262/12131047/9998a6b8-b40f-11e5-8001-d91f185dc8c1.png">

I am using the Mac OS terminal with bash

**Comment by emilniklas** [comment]
Are you perhaps using `pub run` to run your script? Then this is a known issue: dart-lang/pub#1204
Cupid falls back to non colored output when the output device is not a terminal (eg. log file or Windows console), and Dart's subprocess is not a Terminal.

**Comment by lejard-h** [comment]
No `pub run`, directly `polymer_app`

**Comment by lejard-h** [comment]
Oh okay I understand now.

Effectively I'am using `pub run`
When I am using `dart bin/polymer.dart` I have color.

Sorry

**Comment by emilniklas** [comment]
No problem! Good luck!
