### ISSUE TITLE
in a dark terminal, some colors seem to be to dark

### ISSUE THREAD

**Issue by kasperpeulen** [dart-bridge/cupid#5]
![image](https://cloud.githubusercontent.com/assets/1035299/10559572/4a156cd4-74f4-11e5-84aa-29125835fbaa.png)

Not really sure how this is normally done, but I guess it is possible to do some logic so that dark colors become light in a dark terminal, and light colors become darker in a light terminal?

**Comment by emilniklas** [comment]
The colors in the terminal is determined by the terminal client in question (WebStorm, iTerm2, [native] Terminal etc.). Go into the settings of your terminal app and see if you can bump up the contrast!

However the gray color is supposed to look muted.
