### ISSUE TITLE
Make `SendPort connector` argument optional?

### ISSUE THREAD

**Issue by kasperpeulen** [dart-bridge/cupid#8]
I feel like `SendPort connector` should be an optional argument:

https://www.dartdocs.org/documentation/cupid/0.9.9/cupid/cupid.html

Just a minor thing, great package!

**Comment by emilniklas** [comment]
This helper function should ONLY be used directly with main:

``` dart
main(_, __) => cupid(new MyProgram(), _, __);
```

The thing is that to support restarts, Cupid spawns the same script as it is running but with a SendPort as the Isolate message. There is no use case for running `cupid(program, args, null)`, ever.

If you need to run a program in code (for testing or whatever), you should use the `run` method on your program:

``` dart
new MyProgram().run();
```

https://www.dartdocs.org/documentation/cupid/0.9.9/cupid/Program/run.html

**Comment by kasperpeulen** [comment]
@emilniklas Okay, but then, if there is no use case for ever doing `cupid(program, args, null)`, I would expect an error, if I do this :)

**Comment by emilniklas** [comment]
Well, it is the expected input. it's just that the third argument must be the second argument from main, which can be null.

**Comment by kasperpeulen** [comment]
ah, like that, I understand, thanks
